function list = undec_list_fast( bitdepth )
%function generating full list of all undecimal numbers, but all entries
%range from 1 to 11 instead of 0 to 10
%   


if bitdepth == 1
  list = (1:11)';  
else
  list_min_1 = undec_list_fast(bitdepth-1);
  list = [1 * ones(11^(bitdepth-1),1), list_min_1; ...
          2 * ones(11^(bitdepth-1),1), list_min_1; ...
          3 * ones(11^(bitdepth-1),1), list_min_1; ...
          4 * ones(11^(bitdepth-1),1), list_min_1; ...
          5 * ones(11^(bitdepth-1),1), list_min_1; ...
          6 * ones(11^(bitdepth-1),1), list_min_1; ...
          7 * ones(11^(bitdepth-1),1), list_min_1; ...
          8 * ones(11^(bitdepth-1),1), list_min_1; ...
          9 * ones(11^(bitdepth-1),1), list_min_1; ...
          10* ones(11^(bitdepth-1),1), list_min_1; ...
          11* ones(11^(bitdepth-1),1), list_min_1];
end



end

